# Sua chave de ativação
chave: 'key'
# Nome do lobby atual para o uso no menu de lobbies, config: lobbies.yml
lobby: 'skywars'
# Localização do spawn
spawn: null

#tenta usar em localhost so de teste.